name: ci-cd myits-event be

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy be
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              export PATH=$PATH:/usr/local/go/bin
              cd /var/www/myits-event-be
              git stash
              git checkout main
              git pull --rebase origin main
              git status
              go build -o main main.go
              go run main.go --migrate
              sudo systemctl restart myits-event-be.service
              sudo systemctl status myits-event-be.service --no-pager
